name: maukos_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # google
  google_fonts: ^4.0.3

  # flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0

  # other
  get_it: ^7.2.0
  intl: ^0.18.0
  unicons: ^2.1.0
  lottie: ^2.3.2
  another_flushbar: ^1.12.29
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#008585"
  image: assets/images/logo.png
  # android_12:
  #   color: "#008585"
  #   image: assets/images/logo.png
  web: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg
